---
title: "Plot forests and parks in Ghana"
author: "Himal Shrestha"
date: "10/09/2022"
output: 
  md_document:
    variant: markdown_github
    toc: yes
    toc_depth: 4
---
```{r setup, echo=FALSE}
knitr::opts_knit$set(root.dir = "C:/Users/19226876/OneDrive - LA TROBE UNIVERSITY/1_Projects/transition_ghana_LG/landscape_genetics_ghana")
```

# Aim
- To plot the parks and forest reserves along with the map of Ghana

## Load libraries
```{r}
library(raster)
library(rgdal)
library(rgeos)
library(sp)
library(ggplot2)
library(sf)
library(tmap)
library(raster)
library(ggspatial)
library(ggrepel)
```

```{r}
extrafont::loadfonts(device="win", quiet = TRUE)
```

```{r}
rm(list = ls())
```

## Get Data
```{r}
# Ghana maps
ghana_map_1 <- readOGR("data/gadm41_GHA_shp/gadm41_GHA_1.shp", verbose = FALSE) %>% st_as_sf()
ghana_map_2 <- readOGR("data/gadm41_GHA_shp/gadm41_GHA_2.shp", verbose = FALSE) # %>% st_as_sf()

bbox_buffer <- readOGR("data/bbox_buffer_shp/bbox_buffer_wgs84.shp") %>% st_as_sf() %>% st_transform(crs = crs(ghana_map_1))

ghana_parks <- readOGR("data/forests_parks/Forest_and_Game_Reserves.shp", verbose = FALSE) %>% st_as_sf() %>% st_transform(crs = crs(ghana_map_1))
```

## Visualise data

- extract only Bui national park
```{r}
forest_reserves <- ghana_parks %>% dplyr::filter(Type == "Forest_reserves")
bui_np <- ghana_parks %>% dplyr::filter(ID == "Bui NP")

bui_np_crop <- st_intersection(bui_np, bbox_buffer) # crop national park to the transition region boundary
# ghana_map_1_crop <- st_intersection(ghana_map_1, bbox_buffer) # crop ghana administrative borders to the transition region boundary

# ghana_map_2_crop <- st_intersection(ghana_map_2, bbox_buffer) # crop ghana administrative borders to the transition region boundary

# plot(st_geometry(bui_np_crop))
```
### Plotting elevation
```{r}
alt_r <- raster::getData('alt', country='GHA')
alt <- trim(mask(alt_r, bbox_buffer))
slope <- raster::terrain(alt, opt='slope')
aspect <- terrain(alt, opt='aspect')

# Calculate hillshade -----------------------------------------------------
hill <- hillShade(slope, aspect, 40, 270)
```


### Get the sample information data
```{r}
sample_info <- read.csv("data/ghana_sampling_sites.csv", stringsAsFactors = TRUE)
```

### Getting river data
```{r}
water_lines <- readOGR("data/GHA_wat/GHA_water_lines_dcw.shp", verbose = FALSE) %>% st_as_sf() %>% st_transform(crs = crs(ghana_map_1))
water_lines_perrennial <- water_lines %>% dplyr::filter(HYC_DESCRI == "Perennial/Permanent")

water_bodies <- readOGR("data/GHA_wat/GHA_water_areas_dcw.shp", verbose = FALSE) %>% st_as_sf() %>% st_transform(crs = crs(ghana_map_1))
```

## Plot the map using ggplot2
+ Thanks to [this](https://stackoverflow.com/questions/11179666/ggplot2-raster-plotting-does-not-work-as-expected-when-setting-alpha-values)
```{r}
hs <-  hill
dem <- alt

#   Convert rasters TO dataframes for plotting with ggplot
hdf <- rasterToPoints(hs); hdf <- data.frame(hdf)
colnames(hdf) <- c("X","Y","Hill")
ddf <- rasterToPoints(dem); ddf <- data.frame(ddf)
colnames(ddf) <- c("X","Y","DEM")

#   Create vectors for colour breaks
b.hs <- seq(min(hdf$Hill),max(hdf$Hill),length.out=100)
b.dem <- seq(min(ddf$DEM),max(ddf$DEM),length.out=100)
```

```{r}
p <- ggplot() + 
  geom_raster(data = ddf, aes(X, Y, fill = DEM, alpha = 2)) +
  geom_raster(data = hdf, aes(X, Y, alpha = Hill)) +
  scale_fill_gradientn(name="Altitude (m)",colours = terrain.colors(20))+
  guides(fill = guide_colorbar()) +
  scale_alpha(range = c(0, 0.5), guide = "none") +
  coord_equal() + theme_void()

## Boundary
p1 <- p + 
  geom_sf(data = ghana_map_1, col = "black", lwd = 1, lty = 1, alpha = 0.01) +
  # geom_sf(data = ghana_map_2, col = "black", lwd = 1, lty = 1, alpha = 0.01)+
  geom_sf(data = bui_np_crop, col = "black", fill = "lightcyan3", lwd = 0.5, lty = 1, alpha = .9)+
  geom_sf(data = water_lines_perrennial, col = "steelblue", lwd = 0.8) +
  geom_sf(data = water_bodies, fill = "lightblue", col = "black", alpha = .9)+
  scale_y_continuous(name=expression(paste("Latitude (",degree,")")), limits=c(7.627786, 8.809457),expand=c(0,0))+
  scale_x_continuous(name = expression(paste("Longitude (",degree,")")), limits=c(-2.475539, 0.194787),expand=c(0,0))


scale_bar <- p1 +
  annotation_scale(location = "br", width_hint = 0.5) 

direction <- scale_bar +
  annotation_north_arrow(location = "bl", which_north = "true", 
        pad_x = unit(0.05, "in"), pad_y = unit(0.05, "in"),
        style = north_arrow_fancy_orienteering)

p3 <- direction + geom_point(data = sample_info, aes(X, Y, shape = samples), size = 3, fill = "red", alpha = .8, colour = "black", stroke = 1) +
  geom_label_repel(data = sample_info, aes(X, Y, label = pop_id), size = 5, alpha = 1) + theme_bw(base_family = "Arial", base_size = 18) + scale_shape_manual(values = c(21,24)) #, shape = 21, colour = "black", fill = "white",  alpha = 0.8) # +
  # facet_wrap(~samples, ncol = 1)


p3$labels$shape <- "Samples" #"Sample size"

ggsave(plot = p3, filename = "figs/220923_sample_locations_vec_par.png", device = "png", dpi = 500, width = 9, height = 5, units = "in" )
```

#### Vector samples
```{r}
sample_info_vectors <- sample_info %>% dplyr::filter(samples == "vectors")

vector_only <- direction + geom_point(data = sample_info_vectors, aes(X, Y, size = sample_numbers), shape = 21, fill = "white", alpha = 1, colour = "black", stroke = 1) +
  geom_label_repel(data = sample_info_vectors, aes(X, Y, label = pop_id), size = 5, alpha = 1) + theme_bw(base_family = "Arial", base_size = 18)

vector_only$labels$size <- "Sample size"

ggsave(plot = vector_only, filename = "figs/220923_sample_locations_vector_only.png", device = "png", dpi = 500, width = 9, height = 5, units = "in" )
```

#### Parasite samples
```{r}
sample_info_parasites <- sample_info %>% dplyr::filter(samples == "parasites")

parasite_only <- direction + geom_point(data = sample_info_parasites, aes(X, Y, size = sample_numbers), shape = 21, fill = "white", alpha = 1, colour = "black", stroke = 1) +
  geom_label_repel(data = sample_info_parasites, aes(X, Y, label = pop_id), size = 5, alpha = 1) + theme_bw(base_family = "Arial", base_size = 18)

parasite_only$labels$size <- "Sample size"

ggsave(plot = parasite_only, filename = "figs/220923_sample_locations_par_onlt.png", device = "png", dpi = 500, width = 9, height = 5, units = "in" )
```
### Find which locations belong to which region
```{r}
sample_info_spdf <- SpatialPointsDataFrame(coords = sample_info[,c("X", "Y")], data = sample_info,
                               proj4string = crs(ghana_map_2))

sample_info_region <- sample_info_spdf %over% ghana_map_2
sample_info_region <- sample_info_region %>% dplyr::select(NAME_1, NAME_2)

sample_info$region <- sample_info_region$NAME_1 %>% as.factor()

sample_info$district <- sample_info_region$NAME_2 %>% as.factor()
```

```{r}
tmap_mode("view")
p_tm <- tm_shape(ghana_map_1) + tm_polygons(alpha = .01) + tm_shape(sample_info_spdf) + tm_dots()
```

```{r}
p_tm <- tm_shape(forest_reserves) + tm_polygons(alpha = .01)
```

